version: '3.3'
services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${TSANYELA_DB_USER}
      POSTGRES_PASSWORD: ${TSANYELA_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - './_data:/var/lib/postgresql/data'
