#! /bin/bash

if [ "$1" == "stop" ]
then
    docker compose -f docker-compose.dev.yml down 
else
    docker compose -f docker-compose.dev.yml down && \
    docker compose -f docker-compose.dev.yml up -d --build && \
    docker compose -f docker-compose.dev.yml logs --tail 1000 -f
fi